version: '3.7'
services:

  mysql:
    image: mysql:8
    container_name: mysql
    volumes:
      - ./sources/clickandcollect.sql:/docker-entrypoint-initdb.d/init.sql
      - ./.docker-volumes/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: clickandcollect
    networks:
      - backend
    ports:
      - 3306:3306

  adminer:
    container_name: adminer
    image: adminer:4
    restart: always
    ports:
      - 9080:8080
    networks:
      - backend
    environment:
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      - mysql
    
networks:
  backend: {}